### ISSUE TITLE
`recipe:` behaves weird

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/recipe-format#14]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

recipe:
  version: ${{ version }}
  build:
    number: 0
```

`name` shouldn't be strictly required, also it's weird that it says `The package version.` in the description

![image](https://github.com/prefix-dev/recipe-format/assets/29506042/fc4eb3c0-30e2-4cc9-9b72-cb560f094101)
