### ISSUE TITLE
`test.requires` is not in schema

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/recipe-format#3]
![image](https://github.com/prefix-dev/recipe-format/assets/29506042/0befc0dd-2703-496d-a788-2b75a7dfd0ff)

```yml
test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - my_package
```

**Comment by pavelzw** [comment]
Is the goal that this gets replaced by the following?

```yml
test:
  - imports:
    - my_package
  - extra_requirements:
      run:
        - pip
    script:
      - pip check
```
